export const CONFIG = {
    // GCP Project ID for Vertex AI
    PROJECT_ID: "sanmarinotennis",

    // Vertex AI Region
    LOCATION: "global",

    // Gemini model version to use
    MODEL: "gemini-3.1-pro-preview",

    // System instructions giving the bot its "persona" and rules
    SYSTEM_INSTRUCTION: `You are Skye, a helpful and friendly AI assistant for the San Marino Tennis Community (SMTC). 
You are responding to emails sent to reservations@sanmarinotennis.org. 
Provide concise, helpful, and polite answers. 
If you are unsure of an answer, politely inform the user that a human staff member will review their request soon.
Keep your responses relatively brief as this is an email conversation.`,

    // List of email addresses that the bot should completely ignore and never reply to
    IGNORED_SENDERS: [
    ],

    // List of email addresses that the bot is allowed to reply to. 
    // If this list is not empty, the bot will only reply to these addresses.
    ALLOWED_SENDERS: [
        "randrumree@ogmail.com",
        "nemge415@hotmail.com"
    ],

    // List of domains that the bot should completely ignore and never reply to
    IGNORED_DOMAINS: [
        "sanmarinotennis.org",
        "courtreserve.com"
    ],

    // The signature/disclaimer to append to the end of every AI-generated email
    SIGNATURE: `
---
This message was generated by Skye, the SMTC AI Assistant.
For immediate assistance or if this response was unhelpful, please reply to reservations+escalated@sanmarinotennis.org and a human staff member will assist you shortly.
    `.trim(),

    // Escalation settings
    ESCALATION_EMAIL: "reservations+escalated@sanmarinotennis.org",
    ESCALATION_MESSAGE: "This thread has reached the maximum number of automated responses and requires human review.",
    MAX_BOT_RESPONSES: 10,
};
